"""Generate levels/microban.js from levels/microban.txt (David W. Skinner's Microban, XSB format).

The game is a set of ES modules served statically, so the levels are inlined as a JS array instead of
being fetched. Each level is kept verbatim as its XSB rows (CR stripped, trailing blank lines dropped);
utils.js turns the rows into the game's board strings at load time.

Checks done here so a bad level fails at build time, never inside the browser:
  * only the XSB characters  # space . $ * @ +  occur
  * exactly one player per level
  * the player's reachable area (walking through floor and boxes alike) never touches the bounding
    rectangle, so the game can index board[y-1], board[y+2] etc. without bounds checks, exactly as it
    does for its original level

Run:  python games/sokoban/levels/build_levels.py
"""
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE / "microban.txt"
DST = HERE / "microban.js"
XSB = set("# .$*@+")


def parse(text):
    levels, cur = [], None
    for raw in text.replace("\r\n", "\n").replace("\r", "\n").split("\n"):
        line = raw.rstrip("\n")
        if line.startswith(";"):
            if cur is not None:
                levels.append(cur)
            cur = {"title": line[1:].strip(), "rows": []}
        elif line.strip() == "":
            continue
        else:
            if cur is None:
                raise SystemExit(f"board row before the first title line: {line!r}")
            cur["rows"].append(line)
    if cur is not None:
        levels.append(cur)
    return levels


def check(n, rows):
    chars = set("".join(rows)) - XSB
    if chars:
        raise SystemExit(f"level {n}: unexpected characters {sorted(chars)}")
    players = sum(r.count("@") + r.count("+") for r in rows)
    if players != 1:
        raise SystemExit(f"level {n}: {players} players")
    boxes = sum(r.count("$") + r.count("*") for r in rows)
    goals = sum(r.count(".") + r.count("*") + r.count("+") for r in rows)
    if boxes < goals:
        raise SystemExit(f"level {n}: {boxes} boxes for {goals} goals, cannot be solved")
    w, h = max(map(len, rows)), len(rows)
    grid = [r.ljust(w) for r in rows]
    py, px = next((y, r.index("@") if "@" in r else r.index("+")) for y, r in enumerate(grid) if "@" in r or "+" in r)
    seen, stack = {(px, py)}, [(px, py)]
    while stack:
        x, y = stack.pop()
        if x in (0, w - 1) or y in (0, h - 1):
            raise SystemExit(f"level {n}: reachable cell ({x},{y}) lies on the border, level is not enclosed")
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            nx, ny = x + dx, y + dy
            if grid[ny][nx] != "#" and (nx, ny) not in seen:
                seen.add((nx, ny)); stack.append((nx, ny))
    return w, h, boxes, goals


def js_string(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def main():
    levels = parse(SRC.read_text(encoding="utf-8"))
    out = [
        "// Generated by build_levels.py from microban.txt. Do not edit by hand; edit the txt and rerun the script.",
        "// Microban, %d levels, by David W. Skinner (terms in CREDITS.md). Each level is its XSB rows, verbatim:" % len(levels),
        "// '#' wall, ' ' floor, '.' goal, '$' box, '*' box on goal, '@' player, '+' player on goal. Rows may be ragged;",
        "// utils.js pads them with floor when it builds the board.",
        "export const MICROBAN = [",
    ]
    big = 0
    for i, lv in enumerate(levels):
        w, h, boxes, goals = check(i + 1, lv["rows"])
        big += max(w, h) > 12
        out.append(f"  // {lv['title']}  ({w}x{h}, {boxes} boxes)")
        out.append("  [" + ", ".join(js_string(r) for r in lv["rows"]) + "],")
    out.append("]")
    out.append("")
    DST.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {DST.relative_to(HERE.parents[2])}: {len(levels)} levels, {big} wider or taller than 12 cells")


if __name__ == "__main__":
    sys.exit(main())
